name: Spring Boot CD

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: 소유자명 소문자 변환
        run: echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: GHCR 로그인
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.OWNER }}/gif-server:latest

      - name: 서버 배포 (SSH)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/gif-server
            docker pull ghcr.io/${{ env.OWNER }}/gif-server:latest
            IMAGE_NAME=${{ env.OWNER }}/gif-server docker-compose up -d --remove-orphans
            docker image prune -f

      - name: GIF_SERVER CD Discord Notification (success)
        if: ${{ success() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_GIF_SERVER }}
          title: '✅ 성공 했다능! ✅'
          status: ${{ job.status }}
          description: '서버 배포 성공'
          color: 65280
          username: 'GIF-SERVER-bot'

      - name: GIF_SERVER CD Discord Notification (failure)
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_GIF_SERVER }}
          title: '❗️ 실패했다능! ❗️'
          status: ${{ job.status }}
          description: '서버 배포 실패'
          color: 16711680
          username: 'GIF-SERVER-bot'
